name: "Build and Test"

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */24 * * *'

env:
  BUILD_TYPE: Release

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
    name: Build & Test on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - name: Install cmake
        run: |
          sudo apt update
          sudo apt install -y cmake
      - name: Run cmake
        run: |
          cmake -S ${{github.workspace}}/ -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Run build
        run: |
          cmake --build ${{github.workspace}}/build -j4 --config ${{env.BUILD_TYPE}}
      - name: Run tests
        working-directory: ${{github.workspace}}/build/bin
        run: |
          ./tests/triangle_main_Tests
          ./tests/plplot_main_Tests
      - name: Run application
        working-directory: ${{github.workspace}}/build/bin
        run: |
          ./FEM_Solver square
          ./FEM_Solver box
          ./FEM_Solver bicycle_seat
          ./FEM_Solver square_circle_hole
          ./FEM_Solver double_hex
          ./FEM_Solver face
